from roomie import db
db.create_all()

from roomie import Line

db.session.add(Line(1, 2, 1, 'Go through the left door'))
db.session.add(Line(1, 3, 1, 'Go through the glass door'))
db.session.add(Line(2, 1, 1, 'Turn left at the opposite side of the room'))
db.session.add(Line(2, 5, 1, 'Turn right at the opposite side of the room'))
db.session.add(Line(3, 1, 1, 'Go towards the kitchen and through the glass door'))
db.session.add(Line(3, 4, 1, 'Go to the stairway'))
db.session.add(Line(3, 5, 1, 'Go through the glass door'))
db.session.add(Line(4, 3, 1, 'Go through the glass door'))
db.session.add(Line(4, 15, 1, 'Go down to the first floor'))
db.session.add(Line(4, 30, 1, 'Go up to the third floor'))
db.session.add(Line(5, 2, 1, 'Go along the corridor to the FOX'))
db.session.add(Line(5, 3, 1, 'Go through the glass door at the end of the corridor'))
db.session.add(Line(5, 6, 1, 'Go along the corridor to the Little Prince and through the door on your left'))
db.session.add(Line(5, 7, 1, 'Go along the corridor to the Little Prince'))
db.session.add(Line(5, 9, 1, 'Go to the other side of the Little Prince'))
db.session.add(Line(6, 5, 1, 'Go right'))
db.session.add(Line(6, 7, 1, 'Go left'))
db.session.add(Line(6, 13, 1, 'Go down to the Gallery'))
db.session.add(Line(6, 21, 1, 'Go up to the third floor'))
db.session.add(Line(7, 6, 1, 'Go towards the FOX and through the door on your right'))
db.session.add(Line(7, 8, 1, 'Go along the corridor in the Little Prince and through the door on your left'))
db.session.add(Line(7, 9, 1, 'Go along the corridor in the Little Prince towards Hajos street'))
db.session.add(Line(8, 7, 1, 'Go right'))
db.session.add(Line(8, 9, 1, 'Go left'))
db.session.add(Line(8, 23, 1, 'Go up to the third floor'))
db.session.add(Line(8, 29, 1, 'Go down to the Gallery'))
db.session.add(Line(9, 5, 1, 'Go to the other side of the Little Prince'))
db.session.add(Line(9, 7, 1, 'Go along the corridor'))
db.session.add(Line(9, 8, 1, 'Go towards the Little Prince and through the door on your right'))
db.session.add(Line(9, 10, 1, 'Go through the white door'))
db.session.add(Line(10, 9, 1, 'Go through the white door on your left'))
db.session.add(Line(10, 11, 1, 'Go towards the other side of the room and through the glass door on your right side'))
db.session.add(Line(10, 12, 1, 'Go along the room and turn right'))
db.session.add(Line(11, 10, 1, 'Go left'))
db.session.add(Line(11, 12, 1, 'Turn right'))
db.session.add(Line(11, 19, 1, 'Go down to the first floor'))
db.session.add(Line(11, 27, 1, 'Go up to the third floor'))
db.session.add(Line(11, 26, 1, 'Go up to the third floor'))
db.session.add(Line(12, 10, 1, 'Go towards the other side of the room'))
db.session.add(Line(12, 11, 1, 'Go towards the other side of the room and through the glass door on your left side'))
db.session.add(Line(13, 6, 1, 'Go up to the second floor'))
db.session.add(Line(13, 21, 1, 'Go up to the third floor'))
db.session.add(Line(13, 29, 1, 'Go towards the other side of the Gallery and through the white door on your left side'))
db.session.add(Line(14, 15, 1, 'Go through the glass door to the stairway'))
db.session.add(Line(15, 4, 1, 'Go up to the first floor'))
db.session.add(Line(15, 14, 1, 'Go right through the glass door'))
db.session.add(Line(15, 16, 1, 'Go left through the glass door'))
db.session.add(Line(16, 15, 1, 'Go left through the glass door'))
db.session.add(Line(16, 17, 1, 'Go right'))
db.session.add(Line(17, 16, 1, 'Go left'))
db.session.add(Line(18, 19, 1, 'Turn right and go through the glass door'))
db.session.add(Line(18, 20, 1, 'Go towards the other side of the room'))
db.session.add(Line(19, 11, 1, 'Go up to the second floor'))
db.session.add(Line(19, 18, 1, 'Go left'))
db.session.add(Line(19, 20, 1, 'Go right'))
db.session.add(Line(19, 27, 1, 'Go up to the third floor'))
db.session.add(Line(19, 26, 1, 'Go up to the third floor'))
db.session.add(Line(20, 19, 1, 'Go through the glass door on your left side'))
db.session.add(Line(20, 18, 1, 'Go towards the other side of the room'))
db.session.add(Line(21, 6, 1, 'Go down to the second floor'))
db.session.add(Line(21, 13, 1, 'Go down to the Gallery'))
db.session.add(Line(22, 24, 1, 'Go to the other side of the floor'))
db.session.add(Line(22, 30, 1, 'Go left'))
db.session.add(Line(23, 8, 1, 'Go down to the second floor'))
db.session.add(Line(23, 26, 1, 'Go to the stairway'))
db.session.add(Line(23, 29, 1, 'Go down to the Gallery'))
db.session.add(Line(23, 30, 1, 'Go right'))
db.session.add(Line(24, 22, 1, 'Go towards the other side of the foor'))
db.session.add(Line(24, 23, 1, 'Go right'))
db.session.add(Line(24, 26, 1, 'Go to the stairway'))
db.session.add(Line(25, 27, 1, 'Go to the stairway'))
db.session.add(Line(25, 28, 1, 'Go towards the other side of the room and turn right'))
db.session.add(Line(26, 27, 1, 'Go upstairs'))
db.session.add(Line(27, 11, 1, 'Go down to the second floor'))
db.session.add(Line(27, 19, 1, 'Go down to the first floor'))
db.session.add(Line(27, 25, 1, 'Go left'))
db.session.add(Line(27, 28, 1, 'Go right'))
db.session.add(Line(28, 25, 1, 'Go towards the other side of the room and turn left'))
db.session.add(Line(28, 27, 1, 'Go left to the stairway'))
db.session.add(Line(29, 8, 1, 'Go up to the second floor'))
db.session.add(Line(30, 24, 1, 'Go right'))


db.session.commit()

Line.query.all()